import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import Head from "next/head";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gifted Natus Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/fonts/Gobold High Bold.otf"
          as="font"
          type="font/otf"
          crossOrigin="anonymous"
        />
        {/* <link
          rel="preload"
          href="/fonts/GoBold-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        /> */}
      </Head>
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
